// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXuRbCQ8GmfaBrCwZ3XSbHUwrdlg_Rflc',
    appId: '1:443354199186:web:ae133433f2e8c10314224b',
    messagingSenderId: '443354199186',
    projectId: 'othello-sensei-3d82a',
    authDomain: 'othello-sensei-3d82a.firebaseapp.com',
    storageBucket: 'othello-sensei-3d82a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0RmVvKI1PUwV7UupZTL10SArsw2nwQf4',
    appId: '1:443354199186:android:a2c11624f7181c0214224b',
    messagingSenderId: '443354199186',
    projectId: 'othello-sensei-3d82a',
    storageBucket: 'othello-sensei-3d82a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrsnyjVEzYHC5E0RP199p1XzzX9DFeu_Q',
    appId: '1:443354199186:ios:3e8489a5562131cf14224b',
    messagingSenderId: '443354199186',
    projectId: 'othello-sensei-3d82a',
    storageBucket: 'othello-sensei-3d82a.firebasestorage.app',
    iosBundleId: 'com.othellosensei.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrsnyjVEzYHC5E0RP199p1XzzX9DFeu_Q',
    appId: '1:443354199186:ios:3e8489a5562131cf14224b',
    messagingSenderId: '443354199186',
    projectId: 'othello-sensei-3d82a',
    storageBucket: 'othello-sensei-3d82a.firebasestorage.app',
    iosBundleId: 'com.othellosensei.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXuRbCQ8GmfaBrCwZ3XSbHUwrdlg_Rflc',
    appId: '1:443354199186:web:7a22d37051c519a014224b',
    messagingSenderId: '443354199186',
    projectId: 'othello-sensei-3d82a',
    authDomain: 'othello-sensei-3d82a.firebaseapp.com',
    storageBucket: 'othello-sensei-3d82a.firebasestorage.app',
  );
}
