// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Checks if the current CPU supports a feature
class FFICpuSupportedFeatures {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FFICpuSupportedFeatures(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FFICpuSupportedFeatures.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  bool CPUHasBMI2() {
    return _CPUHasBMI2();
  }

  late final _CPUHasBMI2Ptr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('CPUHasBMI2');
  late final _CPUHasBMI2 = _CPUHasBMI2Ptr.asFunction<bool Function()>();

  bool CPUHasPopcnt() {
    return _CPUHasPopcnt();
  }

  late final _CPUHasPopcntPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('CPUHasPopcnt');
  late final _CPUHasPopcnt = _CPUHasPopcntPtr.asFunction<bool Function()>();
}
